# Generated by Django 4.2.23 on 2025-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
