# Generated by Django 4.2.24 on 2025-10-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_order_invoice_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
