# Generated by Django 4.2.23 on 2025-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('title', models.CharField(default='Design slider', max_length=100)),
                ('author', models.CharField(default='LUNDEV', max_length=100)),
                ('topic', models.CharField(default='Animal', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
