# Generated by Django 6.0.3 on 2026-06-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingorder',
            name='special_requirements',
        ),
    ]
