# Generated by Django 4.2.24 on 2025-11-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='district',
        ),
    ]
