# Generated by Django 6.0.3 on 2026-06-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingorder',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate_event', 'Corporate_event'), ('formal_event', 'Formal_event'), ('funeral', 'Funeral')], max_length=20),
        ),
    ]
