# Generated by Django 4.2.23 on 2025-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='author',
            field=models.CharField(default='client', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='Dyslexia Adverts', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='topic',
            field=models.CharField(default='Nature of deal', max_length=50),
        ),
    ]
