# Generated by Django 6.0.3 on 2026-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_remove_clothingorder_special_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
