# Generated by Django 4.2.24 on 2025-11-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_rename_city_profile_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='district',
            new_name='city',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
