# Generated by Django 4.2.24 on 2025-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0003_alter_carouselslide_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to='uploads/carouselslide/'),
        ),
        migrations.AlterField(
            model_name='relief',
            name='image',
            field=models.ImageField(upload_to='uploads/relief/'),
        ),
    ]
