# Generated by Django 4.2.23 on 2025-09-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0003_alter_slide_author_alter_slide_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='topic',
        ),
    ]
