# Generated by Django 4.2.24 on 2025-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0004_alter_carouselslide_image_alter_relief_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Or upload a video file.', null=True, upload_to='uploads/video/'),
        ),
    ]
