# Generated by Django 4.2.24 on 2026-04-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0004_vehiclerequest_delete_match_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
