# Generated by Django 4.2.23 on 2025-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0004_remove_slide_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='sec_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='sec_image',
            field=models.ImageField(default='blank', upload_to='site'),
        ),
        migrations.AddField(
            model_name='slide',
            name='sec_title',
            field=models.CharField(default='vvv', max_length=100),
        ),
    ]
