# Generated by Django 4.2.24 on 2026-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0005_vehiclerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerequest',
            name='budget',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='vehicle',
            field=models.CharField(max_length=100),
        ),
    ]
