# Generated by Django 6.0.3 on 2026-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0005_remove_video_video_file_alter_carouselslide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
    ]
