# Generated by Django 6.0.3 on 2026-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0006_alter_vehiclerequest_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='iimport',
            field=models.CharField(default='Windhoek', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='location',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
