# Generated by Django 6.0.3 on 2026-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='relief',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
