# Generated by Django 4.2.23 on 2025-09-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0006_category_customer_order_product_delete_slide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='site/product/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
