# Generated by Django 6.0.3 on 2026-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0007_vehiclerequest_iimport_vehiclerequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerequest',
            name='iimport',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='location',
            field=models.CharField(default='Windhoek', max_length=50),
        ),
    ]
